#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : opus
Version  : 1.1.2
Release  : 2
URL      : http://downloads.xiph.org/releases/opus/opus-1.1.2.tar.gz
Source0  : http://downloads.xiph.org/releases/opus/opus-1.1.2.tar.gz
Summary  : Opus IETF audio codec (@PC_BUILD@ build)
Group    : Development/Tools
License  : BSD-3-Clause
Requires: opus-lib

%description
== Opus audio codec ==
Opus is a codec for interactive speech and audio transmission over the Internet.

%package dev
Summary: dev components for the opus package.
Group: Development
Requires: opus-lib
Provides: opus-devel

%description dev
dev components for the opus package.


%package lib
Summary: lib components for the opus package.
Group: Libraries

%description lib
lib components for the opus package.


%prep
%setup -q -n opus-1.1.2

%build
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -falign-functions=32 -O3 -fno-semantic-interposition -flto "
export FCFLAGS="$CFLAGS -falign-functions=32 -O3 -fno-semantic-interposition -flto "
export FFLAGS="$CFLAGS -falign-functions=32 -O3 -fno-semantic-interposition -flto "
export CXXFLAGS="$CXXFLAGS -falign-functions=32 -O3 -fno-semantic-interposition -flto "
%configure --disable-static --enable-intrinsics --enable-float-approx
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/opus/opus.h
/usr/include/opus/opus_defines.h
/usr/include/opus/opus_multistream.h
/usr/include/opus/opus_types.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc
/usr/share/aclocal/*.m4

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
